format_version: 4
pipelines:
  'prm-deductions-mesh-forwarder':
    group: continuity-service
    label_template: "${COUNT}-${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
          - nems-subscriber/**/*.*
          - gocd/nems-subscriber.gocd.yml
      mesh_forwarder_imported_image:
        pipeline: prm-mesh-aws-forwarder
        stage: build_inbox_forwarder
    stages:
      - import:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - SOURCE_IMAGE_TAG=$GO_DEPENDENCY_LABEL_MESH_FORWARDER_IMPORTED_IMAGE ./tasks _push_forwarder_image_to_repo_ecr
