format_version: 4
common:
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - IMAGE_TAG=$IMAGE_TAG ./tasks promote_docker_image
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - IMAGE_TAG=$IMAGE_TAG ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs
  common_stages: &common_stages
    - deploy:
        clean_workspace: true
        jobs:
          deploy: *deploy_job

pipelines:
  'prm-mesh-forwarder.dev':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      mesh_s3_forwarder_image:
        pipeline: prm-gp2gp-mesh-s3-forwarder
        stage: build_inbox_forwarder
    environment_variables:
      NHS_ENVIRONMENT: dev
      IMAGE_TAG: $IMAGE_TAG
    stages:
      - *common_stages
  'prm-mesh-forwarder.test':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      mesh_s3_forwarder_image:
        pipeline: prm-mesh-forwarder.dev
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: test
      IMAGE_TAG: $IMAGE_TAG
    stages:
      - *common_stages

