format_version: 4
common:
  plan_job: &plan_job
    resources:
      - docker
    artifacts:
      - build:
          source: terraform/nhs_deployment.tfplan
          destination: terraform/
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - IMAGE_TAG=$GO_DEPENDENCY_LABEL_MESH_FORWARDER_IMPORTED_IMAGE ./tasks promote_docker_image
      - exec:
          command: /bin/bash
          arguments:
            - -c
            -  IMAGE_TAG=$GO_DEPENDENCY_LABEL_MESH_FORWARDER_IMPORTED_IMAGE ./tasks tf_plan create
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - fetch:
          stage: plan
          job: plan
          source: terraform/nhs_deployment.tfplan
          destination: terraform/
          is_file: yes
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs
  common_stages: &common_stages
    - plan:
        clean_workspace: true
        jobs:
          plan: *plan_job
    - deploy:
        clean_workspace: true
        jobs:
          deploy: *deploy_job
  prod_stages: &prod_stages
    - plan:
        clean_workspace: true
        jobs:
          plan: *plan_job
    - deploy:
        approval:
          type: manual
          allow_only_on_success: true
        clean_workspace: true
        jobs:
          deploy: *deploy_job

pipelines:
  'prm-deductions-mesh-forwarder.dev':
    group: continuity-service
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
          - nems-subscriber/**/*.*
      mesh_forwarder_imported_image:
        pipeline: prm-mesh-aws-forwarder
        stage: build_inbox_forwarder
      mesh_forwarder_image_import:
        pipeline: prm-deductions-mesh-forwarder
        stage: import
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages: *common_stages
  'prm-deductions-mesh-forwarder.test':
    group: continuity-service
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
          - nems-subscriber/**/*.*
      mesh_forwarder_imported_image:
        pipeline: prm-mesh-aws-forwarder
        stage: build_inbox_forwarder
      mesh_forwarder_dev:
        pipeline: prm-deductions-mesh-forwarder.dev
        stage: deploy
      e2e:
        pipeline: continuity-e2e-tests.dev
        stage: test
    environment_variables:
      NHS_ENVIRONMENT: test
    stages: *common_stages
  'prm-deductions-mesh-forwarder.pre-prod':
    group: continuity-service
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
          - nems-subscriber/**/*.*
      mesh_forwarder_imported_image:
        pipeline: prm-mesh-aws-forwarder
        stage: build_inbox_forwarder
      mesh_forwarder_test:
        pipeline: prm-deductions-mesh-forwarder.test
        stage: deploy
      e2e:
        pipeline: continuity-e2e-tests.test
        stage: test
    environment_variables:
      NHS_ENVIRONMENT: pre-prod
    stages: *common_stages
  'prm-deductions-mesh-forwarder.prod':
    group: continuity-service
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
          - nems-subscriber/**/*.*
      mesh_forwarder_imported_image:
        pipeline: prm-mesh-aws-forwarder
        stage: build_inbox_forwarder
      mesh_forwarder_test:
        pipeline: prm-deductions-mesh-forwarder.pre-prod
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: prod
    stages: *prod_stages

