format_version: 4
pipelines:
  'prm-deductions-mesh-forwarder':
    group: automatic-trigger
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      mesh_forwarder_imported_image:
        pipeline: prm-mesh-aws-forwarder
        stage: build_inbox_forwarder
    stages:
      - import:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - IMAGE_TAG=$GO_DEPENDENCY_LABEL_MESH_FORWARDER_IMPORTED_IMAGE ./tasks _push_registrations_forwarder_image_to_repo_ecr
