format_version: 4
common:
  plan_job: &plan_job
    resources:
      - docker
    artifacts:
      - build:
          source: terraform/nhs_deployment.tfplan
          destination: terraform/
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks promote_docker_image
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - fetch:
          stage: plan
          job: plan
          source: terraform/nhs_deployment.tfplan
          destination: terraform/
          is_file: yes
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs
  common_stages: &common_stages
    - plan:
        clean_workspace: true
        jobs:
          plan: *plan_job
    - deploy:
        clean_workspace: true
        jobs:
          deploy: *deploy_job

pipelines:
  mesh-forwarder.perf:
    group: performance
    label_template: "${COUNT}-${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
          - nems-subscriber/**/*.*
      app:
        pipeline: mesh-forwarder
        stage: promote.test
    environment_variables:
      NHS_ENVIRONMENT: perf
    stages: *common_stages
