format_version: 4
pipelines:
  "prm-mesh-forwarder":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
        destination: prm-deductions-mesh-forwarder
      s3-forwarder:
        git: https://github.com/nhsconnect/prm-gp2gp-mesh-s3-forwarder.git
        branch: master
        destination: prm-gp2gp-mesh-s3-forwarder
    stages:
      - publish-docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - exec:
                    working_directory: prm-gp2gp-mesh-s3-forwarder
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish-docker
